# Generated by Django 4.1.3 on 2022-12-12 06:07

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('categorie', models.CharField(choices=[('AR', 'Architecture'), ('AI', 'Artificial Intelligence'), ('BI', 'Bioinformatics'), ('BE', 'Biomedical Engineering'), ('BT', 'Biotechnology'), ('CS', 'Computer software and applications'), ('CO', 'Computing'), ('EG', 'Engineering'), ('IP', 'Image Processing'), ('IT', 'Information Technology'), ('IN', 'Internet and World Wide Web'), ('MA', 'Manufacturing'), ('NT', 'Nanotechnology and Smart Materials'), ('PP', 'Polymers and Plastics'), ('RG', 'Renewable & Green Energy'), ('RB', 'Robotics'), ('SA', 'Space Environment and Aviation Technology'), ('SE', 'Systems Engineering')], default='AR', max_length=2)),
                ('statut', models.CharField(choices=[('0', 'En attente'), ('1', 'Refusé avec commentaires'), ('2', 'Accepté avec commentaires mineurs'), ('3', 'Accepté avec commentaires majeurs'), ('4', 'Accepté sans commentaire')], default='0', max_length=2)),
                ('titre', models.TextField()),
                ('description', models.TextField(default='')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='ArticleAuteur',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='SoumissionArticle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titre', models.TextField()),
                ('created', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
