# Generated by Django 4.1.3 on 2022-12-12 06:07

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('soumissionArticle', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='articleauteur',
            name='auteur_principal',
            field=models.ForeignKey(editable=False, on_delete=django.db.models.deletion.CASCADE, related_name='article_auteur_principal', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='articleauteur',
            name='auteurs_secondaires',
            field=models.ManyToManyField(related_name='article_auteurs_secondaires', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='article',
            name='auteur',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='soumissionArticle.articleauteur'),
        ),
    ]
