# Generated by Django 4.1.3 on 2022-12-19 04:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('soumissionArticle', '0003_article_auteurs_secondaires_alter_article_auteur_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='soumissionarticle',
            name='titre',
        ),
        migrations.AddField(
            model_name='soumissionarticle',
            name='lien',
            field=models.TextField(default=''),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='soumissionarticle',
            name='statut',
            field=models.CharField(choices=[('0', 'En attente'), ('1', 'Refusé avec commentaires'), ('2', 'Accepté avec commentaires mineurs'), ('3', 'Accepté avec commentaires majeurs'), ('4', 'Accepté sans commentaire')], default='0', max_length=2),
        ),
        migrations.AlterField(
            model_name='article',
            name='statut',
            field=models.CharField(choices=[('0', 'En attente'), ('1', 'Relecture'), ('2', 'Camera Ready'), ('3', 'Publié')], default='0', max_length=2),
        ),
    ]
