# Generated by Django 4.1.3 on 2022-12-19 15:41

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('soumissionArticle', '0005_soumissionarticle_article'),
    ]

    operations = [
        migrations.CreateModel(
            name='Comite',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_limite_evaluation', models.DateTimeField()),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('article', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='soumissionArticle.article')),
                ('evaluateurs', models.ManyToManyField(to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
