# Generated by Django 4.1.3 on 2022-12-19 20:35

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('soumissionArticle', '0006_comite'),
    ]

    operations = [
        migrations.CreateModel(
            name='Commentaire',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField()),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('comite', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='soumissionArticle.comite')),
                ('evaluateur', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('soumission', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='soumissionArticle.soumissionarticle')),
            ],
        ),
    ]
