version: "3.1"

services:
  db:
    image: postgres
    restart: always
    environment:
      POSTGRES_PASSWORD: example
    ports:
      - 5433:5432
    volumes:
      - postgres:/var/lib/postgresql/data

  adminer:
    image: adminer
    restart: always
    ports:
      - 3010:8080
volumes:
  postgres:
